name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # Or the branch you want to trigger the deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy code to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} 'cd /var/www/laravel && git pull origin main && composer install --no-interaction --prefer-dist && php artisan migrate --force && php artisan config:clear && php artisan cache:clear && php artisan config:cache && sudo systemctl restart nginx'
