name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.1  # Use the latest version

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0  # Ensure this is the latest version
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy code to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            set -e
            cd /var/www/laravel
            
            git fetch origin
            git checkout main
            git reset --hard origin/main
            
            composer install --no-interaction --prefer-dist
            php artisan migrate --force
            
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            
            sudo systemctl restart nginx
          EOF
