name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # or the name of the branch you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@latest  # Updated to the latest version

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0  # Updated to v0.7.0
        with:
          ssh-private-key: ${{ secrets.DO_SSH_KEY }}

      - name: Deploy code to Droplet
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DO_USER }}@${{ secrets.DO_HOST }} << 'EOF'
            set -e  # Exit immediately if a command exits with a non-zero status
            cd /var/www/laravel
            
            # Fetch the latest changes
            git fetch origin
            
            # Ensure we are on the main branch and reset any local changes
            git checkout main
            git reset --hard origin/main
            
            # Install dependencies and run migrations
            composer install --no-interaction --prefer-dist
            php artisan migrate --force
            
            # Clear and cache configuration
            php artisan config:clear
            php artisan cache:clear
            php artisan config:cache
            
            # Restart Nginx
            sudo systemctl restart nginx
          EOF
